// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: src/proto/data_processor.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProcessCSVFileRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CsvFilePath    string                 `protobuf:"bytes,1,opt,name=csv_file_path,json=csvFilePath,proto3" json:"csv_file_path,omitempty"`
	AccountId      string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	SkipDuplicates bool                   `protobuf:"varint,3,opt,name=skip_duplicates,json=skipDuplicates,proto3" json:"skip_duplicates,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProcessCSVFileRequest) Reset() {
	*x = ProcessCSVFileRequest{}
	mi := &file_src_proto_data_processor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessCSVFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessCSVFileRequest) ProtoMessage() {}

func (x *ProcessCSVFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_data_processor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessCSVFileRequest.ProtoReflect.Descriptor instead.
func (*ProcessCSVFileRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_data_processor_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessCSVFileRequest) GetCsvFilePath() string {
	if x != nil {
		return x.CsvFilePath
	}
	return ""
}

func (x *ProcessCSVFileRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *ProcessCSVFileRequest) GetSkipDuplicates() bool {
	if x != nil {
		return x.SkipDuplicates
	}
	return false
}

type ProcessCSVFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Stats         *ProcessingStats       `protobuf:"bytes,3,opt,name=stats,proto3" json:"stats,omitempty"`
	Errors        []string               `protobuf:"bytes,4,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessCSVFileResponse) Reset() {
	*x = ProcessCSVFileResponse{}
	mi := &file_src_proto_data_processor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessCSVFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessCSVFileResponse) ProtoMessage() {}

func (x *ProcessCSVFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_data_processor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessCSVFileResponse.ProtoReflect.Descriptor instead.
func (*ProcessCSVFileResponse) Descriptor() ([]byte, []int) {
	return file_src_proto_data_processor_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessCSVFileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ProcessCSVFileResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ProcessCSVFileResponse) GetStats() *ProcessingStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *ProcessCSVFileResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

type ProcessCSVDataRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CsvData        string                 `protobuf:"bytes,1,opt,name=csv_data,json=csvData,proto3" json:"csv_data,omitempty"`
	AccountId      string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	SkipDuplicates bool                   `protobuf:"varint,3,opt,name=skip_duplicates,json=skipDuplicates,proto3" json:"skip_duplicates,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProcessCSVDataRequest) Reset() {
	*x = ProcessCSVDataRequest{}
	mi := &file_src_proto_data_processor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessCSVDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessCSVDataRequest) ProtoMessage() {}

func (x *ProcessCSVDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_data_processor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessCSVDataRequest.ProtoReflect.Descriptor instead.
func (*ProcessCSVDataRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_data_processor_proto_rawDescGZIP(), []int{2}
}

func (x *ProcessCSVDataRequest) GetCsvData() string {
	if x != nil {
		return x.CsvData
	}
	return ""
}

func (x *ProcessCSVDataRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *ProcessCSVDataRequest) GetSkipDuplicates() bool {
	if x != nil {
		return x.SkipDuplicates
	}
	return false
}

type ProcessCSVDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Stats         *ProcessingStats       `protobuf:"bytes,3,opt,name=stats,proto3" json:"stats,omitempty"`
	Errors        []string               `protobuf:"bytes,4,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessCSVDataResponse) Reset() {
	*x = ProcessCSVDataResponse{}
	mi := &file_src_proto_data_processor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessCSVDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessCSVDataResponse) ProtoMessage() {}

func (x *ProcessCSVDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_data_processor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessCSVDataResponse.ProtoReflect.Descriptor instead.
func (*ProcessCSVDataResponse) Descriptor() ([]byte, []int) {
	return file_src_proto_data_processor_proto_rawDescGZIP(), []int{3}
}

func (x *ProcessCSVDataResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ProcessCSVDataResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ProcessCSVDataResponse) GetStats() *ProcessingStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *ProcessCSVDataResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

type ValidateCSVDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CsvData       string                 `protobuf:"bytes,1,opt,name=csv_data,json=csvData,proto3" json:"csv_data,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateCSVDataRequest) Reset() {
	*x = ValidateCSVDataRequest{}
	mi := &file_src_proto_data_processor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateCSVDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateCSVDataRequest) ProtoMessage() {}

func (x *ValidateCSVDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_data_processor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateCSVDataRequest.ProtoReflect.Descriptor instead.
func (*ValidateCSVDataRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_data_processor_proto_rawDescGZIP(), []int{4}
}

func (x *ValidateCSVDataRequest) GetCsvData() string {
	if x != nil {
		return x.CsvData
	}
	return ""
}

func (x *ValidateCSVDataRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type ValidateCSVDataResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IsValid        bool                   `protobuf:"varint,1,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	Errors         []*ValidationError     `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	DuplicateCount int32                  `protobuf:"varint,3,opt,name=duplicate_count,json=duplicateCount,proto3" json:"duplicate_count,omitempty"`
	TotalRecords   int32                  `protobuf:"varint,4,opt,name=total_records,json=totalRecords,proto3" json:"total_records,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ValidateCSVDataResponse) Reset() {
	*x = ValidateCSVDataResponse{}
	mi := &file_src_proto_data_processor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateCSVDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateCSVDataResponse) ProtoMessage() {}

func (x *ValidateCSVDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_data_processor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateCSVDataResponse.ProtoReflect.Descriptor instead.
func (*ValidateCSVDataResponse) Descriptor() ([]byte, []int) {
	return file_src_proto_data_processor_proto_rawDescGZIP(), []int{5}
}

func (x *ValidateCSVDataResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

func (x *ValidateCSVDataResponse) GetErrors() []*ValidationError {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *ValidateCSVDataResponse) GetDuplicateCount() int32 {
	if x != nil {
		return x.DuplicateCount
	}
	return 0
}

func (x *ValidateCSVDataResponse) GetTotalRecords() int32 {
	if x != nil {
		return x.TotalRecords
	}
	return 0
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_src_proto_data_processor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_data_processor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_data_processor_proto_rawDescGZIP(), []int{6}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Details       map[string]string      `protobuf:"bytes,4,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_src_proto_data_processor_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_data_processor_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_src_proto_data_processor_proto_rawDescGZIP(), []int{7}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthCheckResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HealthCheckResponse) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

type ProcessingStats struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TotalRecords   int32                  `protobuf:"varint,1,opt,name=total_records,json=totalRecords,proto3" json:"total_records,omitempty"`
	SavedRecords   int32                  `protobuf:"varint,2,opt,name=saved_records,json=savedRecords,proto3" json:"saved_records,omitempty"`
	SkippedRecords int32                  `protobuf:"varint,3,opt,name=skipped_records,json=skippedRecords,proto3" json:"skipped_records,omitempty"`
	ErrorRecords   int32                  `protobuf:"varint,4,opt,name=error_records,json=errorRecords,proto3" json:"error_records,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProcessingStats) Reset() {
	*x = ProcessingStats{}
	mi := &file_src_proto_data_processor_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessingStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessingStats) ProtoMessage() {}

func (x *ProcessingStats) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_data_processor_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessingStats.ProtoReflect.Descriptor instead.
func (*ProcessingStats) Descriptor() ([]byte, []int) {
	return file_src_proto_data_processor_proto_rawDescGZIP(), []int{8}
}

func (x *ProcessingStats) GetTotalRecords() int32 {
	if x != nil {
		return x.TotalRecords
	}
	return 0
}

func (x *ProcessingStats) GetSavedRecords() int32 {
	if x != nil {
		return x.SavedRecords
	}
	return 0
}

func (x *ProcessingStats) GetSkippedRecords() int32 {
	if x != nil {
		return x.SkippedRecords
	}
	return 0
}

func (x *ProcessingStats) GetErrorRecords() int32 {
	if x != nil {
		return x.ErrorRecords
	}
	return 0
}

type ValidationError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LineNumber    int32                  `protobuf:"varint,1,opt,name=line_number,json=lineNumber,proto3" json:"line_number,omitempty"`
	Field         string                 `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	RecordData    string                 `protobuf:"bytes,4,opt,name=record_data,json=recordData,proto3" json:"record_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationError) Reset() {
	*x = ValidationError{}
	mi := &file_src_proto_data_processor_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationError) ProtoMessage() {}

func (x *ValidationError) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_data_processor_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationError.ProtoReflect.Descriptor instead.
func (*ValidationError) Descriptor() ([]byte, []int) {
	return file_src_proto_data_processor_proto_rawDescGZIP(), []int{9}
}

func (x *ValidationError) GetLineNumber() int32 {
	if x != nil {
		return x.LineNumber
	}
	return 0
}

func (x *ValidationError) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *ValidationError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ValidationError) GetRecordData() string {
	if x != nil {
		return x.RecordData
	}
	return ""
}

var File_src_proto_data_processor_proto protoreflect.FileDescriptor

const file_src_proto_data_processor_proto_rawDesc = "" +
	"\n" +
	"\x1esrc/proto/data_processor.proto\x12\x13etcdataprocessor.v1\x1a\x1cgoogle/api/annotations.proto\"\x83\x01\n" +
	"\x15ProcessCSVFileRequest\x12\"\n" +
	"\rcsv_file_path\x18\x01 \x01(\tR\vcsvFilePath\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12'\n" +
	"\x0fskip_duplicates\x18\x03 \x01(\bR\x0eskipDuplicates\"\xa0\x01\n" +
	"\x16ProcessCSVFileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12:\n" +
	"\x05stats\x18\x03 \x01(\v2$.etcdataprocessor.v1.ProcessingStatsR\x05stats\x12\x16\n" +
	"\x06errors\x18\x04 \x03(\tR\x06errors\"z\n" +
	"\x15ProcessCSVDataRequest\x12\x19\n" +
	"\bcsv_data\x18\x01 \x01(\tR\acsvData\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12'\n" +
	"\x0fskip_duplicates\x18\x03 \x01(\bR\x0eskipDuplicates\"\xa0\x01\n" +
	"\x16ProcessCSVDataResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12:\n" +
	"\x05stats\x18\x03 \x01(\v2$.etcdataprocessor.v1.ProcessingStatsR\x05stats\x12\x16\n" +
	"\x06errors\x18\x04 \x03(\tR\x06errors\"R\n" +
	"\x16ValidateCSVDataRequest\x12\x19\n" +
	"\bcsv_data\x18\x01 \x01(\tR\acsvData\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\"\xc0\x01\n" +
	"\x17ValidateCSVDataResponse\x12\x19\n" +
	"\bis_valid\x18\x01 \x01(\bR\aisValid\x12<\n" +
	"\x06errors\x18\x02 \x03(\v2$.etcdataprocessor.v1.ValidationErrorR\x06errors\x12'\n" +
	"\x0fduplicate_count\x18\x03 \x01(\x05R\x0eduplicateCount\x12#\n" +
	"\rtotal_records\x18\x04 \x01(\x05R\ftotalRecords\"\x14\n" +
	"\x12HealthCheckRequest\"\xf2\x01\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12O\n" +
	"\adetails\x18\x04 \x03(\v25.etcdataprocessor.v1.HealthCheckResponse.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa9\x01\n" +
	"\x0fProcessingStats\x12#\n" +
	"\rtotal_records\x18\x01 \x01(\x05R\ftotalRecords\x12#\n" +
	"\rsaved_records\x18\x02 \x01(\x05R\fsavedRecords\x12'\n" +
	"\x0fskipped_records\x18\x03 \x01(\x05R\x0eskippedRecords\x12#\n" +
	"\rerror_records\x18\x04 \x01(\x05R\ferrorRecords\"\x83\x01\n" +
	"\x0fValidationError\x12\x1f\n" +
	"\vline_number\x18\x01 \x01(\x05R\n" +
	"lineNumber\x12\x14\n" +
	"\x05field\x18\x02 \x01(\tR\x05field\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1f\n" +
	"\vrecord_data\x18\x04 \x01(\tR\n" +
	"recordData2\xa6\x04\n" +
	"\x14DataProcessorService\x12\x86\x01\n" +
	"\x0eProcessCSVFile\x12*.etcdataprocessor.v1.ProcessCSVFileRequest\x1a+.etcdataprocessor.v1.ProcessCSVFileResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/process/file\x12\x86\x01\n" +
	"\x0eProcessCSVData\x12*.etcdataprocessor.v1.ProcessCSVDataRequest\x1a+.etcdataprocessor.v1.ProcessCSVDataResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/process/data\x12\x85\x01\n" +
	"\x0fValidateCSVData\x12+.etcdataprocessor.v1.ValidateCSVDataRequest\x1a,.etcdataprocessor.v1.ValidateCSVDataResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/v1/validate\x12t\n" +
	"\vHealthCheck\x12'.etcdataprocessor.v1.HealthCheckRequest\x1a(.etcdataprocessor.v1.HealthCheckResponse\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/healthB;Z9github.com/yhonda-ohishi/etc_data_processor/src/api/pb;pbb\x06proto3"

var (
	file_src_proto_data_processor_proto_rawDescOnce sync.Once
	file_src_proto_data_processor_proto_rawDescData []byte
)

func file_src_proto_data_processor_proto_rawDescGZIP() []byte {
	file_src_proto_data_processor_proto_rawDescOnce.Do(func() {
		file_src_proto_data_processor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_src_proto_data_processor_proto_rawDesc), len(file_src_proto_data_processor_proto_rawDesc)))
	})
	return file_src_proto_data_processor_proto_rawDescData
}

var file_src_proto_data_processor_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_src_proto_data_processor_proto_goTypes = []any{
	(*ProcessCSVFileRequest)(nil),   // 0: etcdataprocessor.v1.ProcessCSVFileRequest
	(*ProcessCSVFileResponse)(nil),  // 1: etcdataprocessor.v1.ProcessCSVFileResponse
	(*ProcessCSVDataRequest)(nil),   // 2: etcdataprocessor.v1.ProcessCSVDataRequest
	(*ProcessCSVDataResponse)(nil),  // 3: etcdataprocessor.v1.ProcessCSVDataResponse
	(*ValidateCSVDataRequest)(nil),  // 4: etcdataprocessor.v1.ValidateCSVDataRequest
	(*ValidateCSVDataResponse)(nil), // 5: etcdataprocessor.v1.ValidateCSVDataResponse
	(*HealthCheckRequest)(nil),      // 6: etcdataprocessor.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),     // 7: etcdataprocessor.v1.HealthCheckResponse
	(*ProcessingStats)(nil),         // 8: etcdataprocessor.v1.ProcessingStats
	(*ValidationError)(nil),         // 9: etcdataprocessor.v1.ValidationError
	nil,                             // 10: etcdataprocessor.v1.HealthCheckResponse.DetailsEntry
}
var file_src_proto_data_processor_proto_depIdxs = []int32{
	8,  // 0: etcdataprocessor.v1.ProcessCSVFileResponse.stats:type_name -> etcdataprocessor.v1.ProcessingStats
	8,  // 1: etcdataprocessor.v1.ProcessCSVDataResponse.stats:type_name -> etcdataprocessor.v1.ProcessingStats
	9,  // 2: etcdataprocessor.v1.ValidateCSVDataResponse.errors:type_name -> etcdataprocessor.v1.ValidationError
	10, // 3: etcdataprocessor.v1.HealthCheckResponse.details:type_name -> etcdataprocessor.v1.HealthCheckResponse.DetailsEntry
	0,  // 4: etcdataprocessor.v1.DataProcessorService.ProcessCSVFile:input_type -> etcdataprocessor.v1.ProcessCSVFileRequest
	2,  // 5: etcdataprocessor.v1.DataProcessorService.ProcessCSVData:input_type -> etcdataprocessor.v1.ProcessCSVDataRequest
	4,  // 6: etcdataprocessor.v1.DataProcessorService.ValidateCSVData:input_type -> etcdataprocessor.v1.ValidateCSVDataRequest
	6,  // 7: etcdataprocessor.v1.DataProcessorService.HealthCheck:input_type -> etcdataprocessor.v1.HealthCheckRequest
	1,  // 8: etcdataprocessor.v1.DataProcessorService.ProcessCSVFile:output_type -> etcdataprocessor.v1.ProcessCSVFileResponse
	3,  // 9: etcdataprocessor.v1.DataProcessorService.ProcessCSVData:output_type -> etcdataprocessor.v1.ProcessCSVDataResponse
	5,  // 10: etcdataprocessor.v1.DataProcessorService.ValidateCSVData:output_type -> etcdataprocessor.v1.ValidateCSVDataResponse
	7,  // 11: etcdataprocessor.v1.DataProcessorService.HealthCheck:output_type -> etcdataprocessor.v1.HealthCheckResponse
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_src_proto_data_processor_proto_init() }
func file_src_proto_data_processor_proto_init() {
	if File_src_proto_data_processor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_src_proto_data_processor_proto_rawDesc), len(file_src_proto_data_processor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_proto_data_processor_proto_goTypes,
		DependencyIndexes: file_src_proto_data_processor_proto_depIdxs,
		MessageInfos:      file_src_proto_data_processor_proto_msgTypes,
	}.Build()
	File_src_proto_data_processor_proto = out.File
	file_src_proto_data_processor_proto_goTypes = nil
	file_src_proto_data_processor_proto_depIdxs = nil
}
